name: cgroups
run-name: Looking at cgroups
on: [push]
jobs:
  cgroups:
    runs-on: ubuntu-latest
    steps:
      - name: /proc/cpuinfo
        run: |
          cat /proc/cpuinfo
      - name: /proc/cgroups
        run: |
          cat /proc/cgroups
      - name: /proc/self/cgroup
        run: |
          cat /proc/self/cgroup
      - name: /proc/self/mountinfo
        run: |
          cat /proc/self/mountinfo
      - name: /sys/fs/cgroup/system.slice/hosted-compute-agent.service
        run: |
          ls /sys/fs/cgroup/system.slice/hosted-compute-agent.service
      - name: /sys/fs/cgroup/system.slice/hosted-compute-agent.service/cpu.max
        run: |
          cat /sys/fs/cgroup/system.slice/hosted-compute-agent.service/cpu.max
